const eventTemplates = [
    {
        id: "event_calm",
        description: "Markets stay calm for a day.",
        type: "global",
        impact: 0,
        rarity: "common",
        baseWeight: 2,
        tags: ["default", "positive"],
    },
    {
        id: "event_lift",
        description: "Macro data pushes optimism for a few companies.",
        type: "global",
        impact: 0.015,
        rarity: "common",
        baseWeight: 2,
        tags: ["positive"],
    },
    {
        id: "event_shock",
        description: "A surprise regulation rattles the market.",
        type: "global",
        impact: -0.025,
        rarity: "rare",
        baseWeight: 1.2,
        tags: ["regulation", "negative", "scandal"],
    },
    {
        id: "earnings-beat-solid",
        description: "The company reports earnings slightly above expectations. Guidance is stable.",
        type: "company",
        rarity: "common",
        baseWeight: 3,
        effects: {
            instantShockPctRange: [0.03, 0.07],
            companyTrendBiasDelta: 0.003,
            durationDays: 3,
        },
        tags: ["fundamentals", "earnings", "positive"],
    },
    {
        id: "earnings-beat-blowout",
        description: "Earnings and revenue crush expectations. Analysts scramble to upgrade.",
        type: "company",
        rarity: "rare",
        baseWeight: 1,
        effects: {
            instantShockPctRange: [0.08, 0.18],
            companyTrendBiasDelta: 0.01,
            sectorTrendBiasDelta: 0.002,
            durationDays: 5,
        },
        tags: ["fundamentals", "earnings", "positive", "momentum"],
    },
    {
        id: "earnings-miss-mild",
        description: "The company slightly misses earnings estimates, citing temporary headwinds.",
        type: "company",
        rarity: "common",
        baseWeight: 3,
        effects: {
            instantShockPctRange: [-0.05, -0.02],
            companyTrendBiasDelta: -0.003,
            durationDays: 3,
        },
        tags: ["fundamentals", "earnings", "negative"],
    },
    {
        id: "earnings-miss-severe",
        description: "Earnings collapse as costs surge and demand fades. Confidence is shaken.",
        type: "company",
        rarity: "uncommon",
        baseWeight: 1,
        effects: {
            instantShockPctRange: [-0.15, -0.08],
            companyTrendBiasDelta: -0.012,
            sectorTrendBiasDelta: -0.002,
            durationDays: 5,
        },
        tags: ["fundamentals", "earnings", "negative", "panic"],
    },
    {
        id: "guidance-raise",
        description: "Management raises forward guidance on strong demand visibility.",
        type: "company",
        rarity: "uncommon",
        baseWeight: 2,
        effects: {
            instantShockPctRange: [0.03, 0.09],
            companyTrendBiasDelta: 0.006,
            durationDays: 5,
        },
        tags: ["forward-looking", "positive"],
    },
    {
        id: "guidance-cut",
        description: "Management lowers guidance, warning of upcoming softness.",
        type: "company",
        rarity: "uncommon",
        baseWeight: 2,
        effects: {
            instantShockPctRange: [-0.09, -0.04],
            companyTrendBiasDelta: -0.007,
            durationDays: 5,
        },
        tags: ["forward-looking", "negative"],
    },
    {
        id: "innovation-breakthrough",
        description: "A breakthrough product or technology is announced, opening new markets.",
        type: "company",
        rarity: "rare",
        baseWeight: 1,
        effects: {
            instantShockPctRange: [0.1, 0.25],
            companyTrendBiasDelta: 0.015,
            sectorTrendBiasDelta: 0.004,
            volatilityMultiplier: 1.4,
            durationDays: 7,
        },
        tags: ["innovation", "growth", "positive", "high-volatility"],
    },
    {
        id: "product-launch-solid",
        description: "A new product launch is well received by early customers.",
        type: "company",
        rarity: "uncommon",
        baseWeight: 2,
        effects: {
            instantShockPctRange: [0.04, 0.1],
            companyTrendBiasDelta: 0.007,
            durationDays: 4,
        },
        tags: ["innovation", "positive"],
    },
    {
        id: "product-launch-flop",
        description: "A highly anticipated launch is met with weak demand and bad reviews.",
        type: "company",
        rarity: "uncommon",
        baseWeight: 1,
        effects: {
            instantShockPctRange: [-0.12, -0.05],
            companyTrendBiasDelta: -0.01,
            volatilityMultiplier: 1.3,
            durationDays: 4,
        },
        tags: ["innovation", "negative"],
    },
    {
        id: "regulation-tighten",
        description: "New rules increase compliance costs and limit growth in this sector.",
        type: "sector",
        rarity: "uncommon",
        baseWeight: 2,
        effects: {
            sectorTrendBiasDelta: -0.01,
            volatilityMultiplier: 1.2,
            durationDays: 6,
        },
        tags: ["policy", "negative"],
    },
    {
        id: "regulation-relief",
        description: "Regulators roll back restrictions, boosting profitability.",
        type: "sector",
        rarity: "rare",
        baseWeight: 1,
        effects: {
            sectorTrendBiasDelta: 0.012,
            volatilityMultiplier: 0.9,
            durationDays: 6,
        },
        tags: ["policy", "positive"],
    },
    {
        id: "supply-shock-negative",
        description: "A supply shock ripples through a critical sector.",
        type: "sector",
        rarity: "uncommon",
        baseWeight: 2,
        effects: {
            sectorTrendBiasDelta: -0.015,
            volatilityMultiplier: 1.4,
            durationDays: 5,
        },
        tags: ["supply-shock", "negative"],
    },
    {
        id: "event_external_crash",
        description: "Outside crash drags every sector down.",
        type: "global",
        impact: -0.05,
        rarity: "legendary",
        baseWeight: 0.5,
        tags: ["panic", "negative"],
    },
    {
        id: "event_sector_momentum",
        description: "Sector-wide momentum favors specialized names.",
        type: "sector",
        impact: 0.02,
        rarity: "uncommon",
        baseWeight: 1.2,
        tags: ["momentum", "positive"],
    },
    {
        id: "event_sector_crunch",
        description: "A supply chain crunch harms the sector.",
        type: "sector",
        impact: -0.02,
        rarity: "uncommon",
        baseWeight: 1.1,
        tags: ["supply-shock", "negative"],
    },
    {
        id: "event_choice_rumor",
        description: "You're offered a rumor — choosing to act could pay off.",
        type: "player_choice",
        impact: 0.04,
        rarity: "epic",
        baseWeight: 0.6,
        tags: ["rumor", "positive"],
    },
    {
        id: "event_player_backstab",
        description: "A trusted contact betrays you, sudden sell-off.",
        type: "player_choice",
        impact: -0.035,
        rarity: "epic",
        baseWeight: 0.6,
        tags: ["scandal", "negative"],
    },
    {
        id: "event_chain_startup",
        description: "Startup funding round incites a cascading pump.",
        type: "company",
        impact: 0.05,
        rarity: "legendary",
        baseWeight: 0.4,
        tags: ["innovation", "positive"],
    },
    {
        id: "event_default_shift",
        description: "Markets drift with a muted shift in tone.",
        type: "global",
        impact: -0.01,
        rarity: "common",
        baseWeight: 2,
        tags: ["default"],
    },
];
export default eventTemplates;
